name: License
on: [
    push,
    pull_request
]
jobs:
  validate-licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: jonabc/setup-licensed@v1
        with:
          version: '2.x'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: licensed list
