name: "Update and check dependency data"
on: [ push, pull_request ]
jobs:
  licensed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{github.ref}} # checkout branch not SHA

      - run: npm install --production

      - name: Run setup-licensed
        uses: ./
        with:
          version: '2.x'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - run: licensed cache
      - uses: jonabc/licensed-ci@v1
        with:
          workflow: branch
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cleanup_on_success: 'true'

      - run: licensed status
