name: License
on: [
    push,
    pull_request
]
jobs:
  validate-licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Licensed CI
        uses: jonabc/licensed-ci@v1.5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
